name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: |
          echo "NIGGERS!!!"
          echo "HOG RIIIIIIIIIIIIDER!!!"
      - name: second-step
        run: echo "Hog is coming for stephan's ass xD"
