name: Matrix
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [18.18.0, 20.9.0, 22.15.0]
        operating-systems: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-systems }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Deps
        run: npm ci
      - name: Build project
        run: npm run build
