name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0
      - name: Install Deps
        run: npm ci
      - name: Test
        run: npm run test
